-- Enable pgcrypto for gen_random_uuid
create extension if not exists pgcrypto;

-- Tables
create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  device_hash text,
  os text,
  region text,
  created_at timestamptz default now()
);

create table if not exists public.captures (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.sessions(id) on delete cascade,
  view text check (view in ('front','left','right')),
  qc_json jsonb,
  meta_json jsonb,
  saved_local_path_hash text,
  created_at timestamptz default now()
);

create table if not exists public.effects (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.sessions(id) on delete cascade,
  effect_id text,
  version text,
  params_json jsonb,
  confidence float8,
  created_at timestamptz default now()
);

create table if not exists public.ratings (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.sessions(id) on delete cascade,
  realism int check (realism between 1 and 5),
  satisfaction int check (satisfaction between 1 and 5),
  regions text[],
  created_at timestamptz default now()
);

create table if not exists public.experts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.sessions(id) on delete cascade,
  clinic_id text,
  advice_json jsonb,
  created_at timestamptz default now()
);

-- RLS and minimal permissions
alter table public.sessions enable row level security;
alter table public.captures enable row level security;
alter table public.effects enable row level security;
alter table public.ratings enable row level security;
alter table public.experts enable row level security;

revoke all on all tables in schema public from anon;
grant insert on public.sessions to anon;
grant insert on public.captures to anon;
grant insert on public.effects to anon;
grant insert on public.ratings to anon;
grant insert on public.experts to anon;

-- Insert-only policies for anon
create policy if not exists p_insert_sessions on public.sessions for insert to anon with check (true);
create policy if not exists p_insert_captures on public.captures for insert to anon with check (true);
create policy if not exists p_insert_effects on public.effects for insert to anon with check (true);
create policy if not exists p_insert_ratings on public.ratings for insert to anon with check (true);
create policy if not exists p_insert_experts on public.experts for insert to anon with check (true);

-- telemetry schema init
create table if not exists public.sessions (
  session_id uuid primary key,
  device_hash text not null,
  os text,
  region text,
  created_at timestamptz default now()
);

create table if not exists public.captures (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(session_id) on delete cascade,
  view text,
  qc_json jsonb,
  meta_json jsonb,
  saved_local_path_hash text,
  created_at timestamptz default now()
);

create table if not exists public.effects (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(session_id) on delete cascade,
  effect_id text not null,
  version text,
  params_json jsonb,
  confidence double precision,
  created_at timestamptz default now()
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(session_id) on delete cascade,
  realism int,
  satisfaction int,
  regions jsonb,
  created_at timestamptz default now()
);

create table if not exists public.experts (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(session_id) on delete cascade,
  clinic_id text,
  advice_json jsonb,
  created_at timestamptz default now()
);

-- RLS
alter table public.sessions enable row level security;
alter table public.captures enable row level security;
alter table public.effects enable row level security;
alter table public.ratings enable row level security;
alter table public.experts enable row level security;

-- policies: require auth, bind to user id claim in session_id namespace (demo uses session only)
create policy if not exists "insert_any_session" on public.sessions for insert to authenticated using (true) with check (true);
create policy if not exists "select_own_session" on public.sessions for select to authenticated using (true);

create policy if not exists "insert_captures" on public.captures for insert to authenticated using (true) with check (true);
create policy if not exists "select_captures" on public.captures for select to authenticated using (true);

create policy if not exists "insert_effects" on public.effects for insert to authenticated using (true) with check (true);
create policy if not exists "select_effects" on public.effects for select to authenticated using (true);

create policy if not exists "insert_ratings" on public.ratings for insert to authenticated using (true) with check (true);
create policy if not exists "select_ratings" on public.ratings for select to authenticated using (true);

create policy if not exists "insert_experts" on public.experts for insert to authenticated using (true) with check (true);
create policy if not exists "select_experts" on public.experts for select to authenticated using (true);


